Issue #742: clean up the final few test regressions; add debugTestSelector option to runRowanTestSuiteV2.stone; fine tune newBuild_test_rowan
1468 run, 1432 passed, 20 failed, 16 errors, 0 deprecationErrors
  errors
	DiskFileSystemTest debug: #testFileNames
	FileHandleTest debug: #testTruncate
	FileReferenceAttributeTests debug: #testCreationTime
	RwBrowserToolApiTest debug: #testMoveGlobalExtensionSessionMethods
	RwBrowserToolApiTest debug: #testNewClassVersionB
	RwHybridBrowserToolTest debug: #testHybridMoveMethodFromSessionMethodsIntoSessionMethods
	RwHybridBrowserToolTest debug: #testHybridMoveMethodIntoSessionMethods
	RwProjectAuditToolTest debug: #test_Issue_535
	RwProjectToolTest debug: #testProjectGlobalsClassesExtensionsInSessionMethods
	RwRowanProjectIssuesTest debug: #testIssue498_constraint_ordering_3
	RwRowanSample9Test debug: #testSpec_0023_1
	RwSymbolDictionaryTest debug: #testClassPropertiesPatch
	RwSymbolDictionaryTest debug: #testClassVariableChangePatch
	RwSymbolDictionaryTest debug: #testClassVersioningPatch
	RwUrlTest debug: #testAsRwRepository
	ZnCharacterEncoderTests debug: #testUTF8Back
  failures
	DirectoryEntryTest debug: #testCreationTimeIsADateAndTimeInstance
	DirectoryEntryTest debug: #testModificationTimeIsADateAndTimeInstance
	FileReferenceAttributeTests debug: #testExists
	FileReferenceAttributeTests debug: #testFileSize
	FileReferenceAttributeTests debug: #testIsCharacter
	FileReferenceAttributeTests debug: #testIsDirectory
	FileReferenceAttributeTests debug: #testIsFile
	FileReferenceAttributeTests debug: #testIsReadable
	FileReferenceAttributeTests debug: #testIsSymlink
	FileReferenceAttributeTests debug: #testIsWriteable
	FileReferenceAttributeTests debug: #testModificationTime
	RowanQueryServicesTest debug: #test_dontUseFileStream
	RwBrowserToolApiTest debug: #testNewClassVersion_session_method_change_extension_method_protocol
	RwBrowserToolApiTest debug: #testNewClassVersion_session_method_change_extension_method_source
	RwBrowserToolApiTest debug: #testNewClassVersion_session_method_unchanged_extension_method_protocol
	RwImplementedButNotSentTest debug: #testImplementedButNotSent
	RwRowanProjectIssuesTest debug: #testIssue208_move_method_from_project_to_project
	RwRowanProjectIssuesTest debug: #testIssue310
	RwRowanProjectIssuesTest debug: #testIssue498_constraint_ordering_1
	RwSentButNotImplementedTest debug: #testSentButNotImplemented

diff --git a/platforms/gemstone/gsdevkit/stones/newBuild_test_rowan b/platforms/gemstone/gsdevkit/stones/newBuild_test_rowan
--- a/platforms/gemstone/gsdevkit/stones/newBuild_test_rowan
+++ b/platforms/gemstone/gsdevkit/stones/newBuild_test_rowan
@@ -1,4 +1,4 @@
-# set -e # don't exit on error ... I want the record script to run at the end ....
+set -e
 
 . defStone.env
 
@@ -17,13 +17,19 @@ newExtent -s product/../hidden/bin/extent0.rowan.dbf $GEMSTONE_NAME
 
 $ROWAN_PROJECTS_HOME/Rowan/platforms/gemstone/gsdevkit/superdoit/rowanAttachGitRepos.stone -D --gemstoneBaseImage --tests -- $GEMSTONE_NAME
 
+#
+# Debug test that only fails during batch run
+#
+# $ROWAN_PROJECTS_HOME/Rowan/platforms/gemstone/gsdevkit/superdoit/runRowanTestSuiteV2.stone -D --debugSelector=testUnmanagedSpec_0057_02 -- $GEMSTONE_NAME
 $ROWAN_PROJECTS_HOME/Rowan/platforms/gemstone/gsdevkit/superdoit/runRowanTestSuiteV2.stone -D -- $GEMSTONE_NAME
 
 #	./rowanTestStats.stone -h -- rowan_test_stats_361
 #
 branch=`git --git-dir=$ROWAN_PROJECTS_HOME/Rowan/.git rev-parse --abbrev-ref HEAD`
 
-branchQuery=`./rowanTestStats.stone lookup --branch=$branch --gsVer=$vers -- rowan_test_stats_361 2>&1`
+set +e # okay for the lookup to fail - the error message is meaningful
+branchQuery=`./rowanTestStats.stone lookup --jsonFile=ignoreMe.json --branch=$branch --gsVer=$vers -- rowan_test_stats_361 2>&1`
+set -e
 if [[ "$branchQuery" == "No sample found matching gsVer"* ]] ; then
 	# this is a branch for which we have no samples with which to compare
 	originalBranch=$branch
