Issue #660: the new bootstrap structure looks to be complete as all four platform tests are passing:
Rowan STON Cypress FileSystemGs tests for GemStone '3.2.15'
1359 run, 1320 passed, 16 failed, 23 errors, 0 deprecationErrors

Rowan STON Cypress FileSystemGs tests for GemStone '3.5.0'
1359 run, 1321 passed, 18 failed, 20 errors, 0 deprecationErrors

Rowan STON Cypress FileSystemGs tests for GemStone '3.6.1'
1404 run, 1360 passed, 22 failed, 22 errors, 0 deprecationErrors

Rowan STON Cypress FileSystemGs tests for GemStone '3.7.0'
1404 run, 1360 passed, 22 failed, 22 errors, 0 deprecationErrors

diff --git a/platforms/gemstone/gsdevkit/stones/newBuild_test_rowan b/platforms/gemstone/gsdevkit/stones/newBuild_test_rowan
--- a/platforms/gemstone/gsdevkit/stones/newBuild_test_rowan
+++ b/platforms/gemstone/gsdevkit/stones/newBuild_test_rowan
@@ -1,17 +1,39 @@
-#! /usr/bin/env bash
+# set -e # don't exit on error ... I want the record script to run at the end ....
 
-set -e
 . defStone.env
-export vers="3.5.0"
+
+vers=`awk 'NR==2{print $1; exit}' product/version.txt`
 
 rm -rf *.log *.out
 
-newExtent -s product/bin/extent0.dbf $GEMSTONE_NAME
+newExtent -s product/../hidden/bin/extent0.rowan.dbf $GEMSTONE_NAME
 
-startTopaz $GEMSTONE_NAME -l << EOF
-	input $ROWAN_PROJECTS_HOME/Rowan/platforms/gemstone/topaz/$vers/installRowanPortableString.tpz
-EOF
+$ROWAN_PROJECTS_HOME/Rowan/platforms/gemstone/topaz/bootstrap/installPortableString.tpz $GEMSTONE_NAME -lq
+$ROWAN_PROJECTS_HOME/Rowan/platforms/gemstone/topaz/rowanRepositoryTestsRootV2.tpz $GEMSTONE_NAME -lq
 
-startTopaz $GEMSTONE_NAME -l << EOF
-	input $ROWAN_PROJECTS_HOME/Rowan/platforms/gemstone/topaz/rowanTestSuite.tpz
-EOF
+# $GS_HOME/shared/repos/Rowan/platforms/gemstone/topaz/$vers/installRowanPortableStringRowanV2.tpz $GEMSTONE_NAME -lq
+
+$GS_HOME/shared/repos/Rowan/platforms/gemstone/topaz/rowanTestSuiteRowanV2.tpz  $GEMSTONE_NAME -T100000 -lq
+
+#	Report
+# ./record.gs.st rowan_test_stats_350 -- --query=summary
+#	Save the testResults.json in the db
+# ./record.gs.st rowan_test_stats_350 -- --load=testResults.json --branch=issue_308
+# ./record.gs.st rowan_test_stats_350 -- --load=testResults.json --branch=issue_308
+#	Update the record with the SHA of the commit
+# ./record.gs.st rowan_test_stats_350 -- --updateSHA=92de7b5  --branch=issue_308 --gsVersion=3.2.15
+# ./record.gs.st rowan_test_stats_350 -- --updateSHA=92de7b5  --branch=issue_308 --gsVersion=3.5.0
+
+branch=`git --git-dir=$ROWAN_PROJECTS_HOME/Rowan/.git rev-parse --abbrev-ref HEAD`
+# branch=masterV2.1
+
+branchQuery=`./record.gs.st rowan_test_stats_350 -- --query --branch=$branch --gsVersion=$vers`
+
+if [ "$branchQuery" = "[ ]" ] ; then
+	# this is a branch for which we have no samples with which to compare, so use issue_308 
+  branch=masterV2.1
+	echo
+	echo "USING DEFAULT BRANCH -- $branch"
+	echo
+fi
+./record.gs.st rowan_test_stats_350 -- --load=testResults.json --branch=$branch --compare=$vers
